### ISSUE TITLE
导不出PNG？

### ISSUE THREAD

**Issue by luobaoan** [fex-team/kityminder#11]
demo上面导不出PNG呢，为什么呢

**Comment by kitygraph** [comment]
您好，PNG导出的问题先检查一下两点：
1. 您的代码是否在最新的版本上，之前的版本PNG导出确实有问题
2. 您是否直接打开 html 文件来运行 Demo，直接访问本地文件由于浏览器的安全机制，不允许导出；如果要运行，请运行在本地服务器上，然后用 localhost 访问

如果确认不是这两个问题，请提供进一步的信息，谢谢！

**Comment by luobaoan** [comment]
谢谢团队这么迅速的答疑！默认的那个状态（新建完只有中心那个控件的时候），可以的，但是元素多了就不行。就只有PNG不行哟。。我是用官方最新版的DEMO测试的哟。

在 2014年3月19日 下午12:19，kitygraph notifications@github.com写道：

**Comment by techird** [comment]
您好，请问使用的是什么浏览器？方便提供浏览器控制台上报的错误信息吗？

**Comment by techird** [comment]
您好，我用您的账号登录并且导出您指定的文件到PNG，已然没法复现您所说的问题。如果可以，提供一下您出错时浏览器控制台的截图，包括浏览器地址栏的截图。感谢您的支持！

------------------ 原始邮件 ------------------
发件人: "luobaoan";notifications@github.com;
发送时间: 2014年3月20日(星期四) 凌晨0:30
收件人: "fex-team/kityminder"kityminder@noreply.github.com; 
抄送: "刘家鸣"techird@qq.com; 
主题: Re: [kityminder] 导不出PNG？ (#11)

chrome 版本 33.0.1750.154 
 刚刚测试了，它好像只针对我其中一个脑图导不出。我新建了两个测试，可以的。 
 我百度的临时账户： 
 luobaoan 
 luobaoan123456 
 管理员可以上去看看，我设置的是临时密码，而且上面没有任何私密信息，大家只为技术交流。授权访问。请上去之后选择“会员系统”的脑图。 

 2014-03-19 22:24 GMT+08:00 techird notifications@github.com:

**Comment by luobaoan** [comment]
OK。谢谢团队耐心解答。可能是我个别原因。希望该产品越做越好！真的非常不错！

在 2014年3月20日 下午12:46，techird notifications@github.com写道：

**Comment by techird** [comment]
未能复现问题，暂时关闭
