### ISSUE TITLE
不能单独设置字体粗细、斜体，同时不能换行，重命名文件

### ISSUE THREAD

**Issue by imEhllBdPGMVaArZ** [fex-team/kityminder#111]
当想设置某个属于为粗体或者斜体的时候，是加粗或倾斜整个节点而非想要的单个文字加粗倾斜，可以增加颜色标注类似label标签这些? 换行的下面看到有加入了~~所以就无视吧~

貌似不能重命名文件，要到网盘里面更改才行

当然这些只是表象的，不是功能上的~~所以只是建议而已。

**Comment by techird** [comment]
富文本编辑咱不会支持
换行新版本已支持(Shift+Enter)
文件重命名将在下个版本支持
