### ISSUE TITLE
Chrome插件的离线版本

### ISSUE THREAD

**Issue by Alsiso** [fex-team/kityminder#112]
希望可以跟进Chrome浏览器的离线版本，这样使用起来就更方便了； 我是不是要求太苛刻 - -！

**Comment by leixu2txtek** [comment]
嗯，这个要求有点高呀！   :))

不过完全可以做到的嘛，那楼主赞助点 chrome 插件开发费用。  ;)))

**Comment by Alsiso** [comment]
@leixu2txtek 来杭州，一人一杯咖啡伺候
