### ISSUE TITLE
资源请增加删除功能

### ISSUE THREAD

**Issue by prostickman** [fex-team/kityminder#113]
人力资源需要增加删除功能

**Comment by techird** [comment]
您好，现在是可以删除的，直接取消资源面板上的对勾即可

![image](https://cloud.githubusercontent.com/assets/1901286/3852023/2cec23be-1ea1-11e4-8cb4-5f0c959281b6.png)

**Comment by prostickman** [comment]
希望在资源面板的上面的资源也能删除

如上图，希望能删除 隔壁老王
