### ISSUE TITLE
连续插入多个兄弟节点出现定位异常

### ISSUE THREAD

**Issue by ningmuyy** [fex-team/kityminder#115]
![image](https://cloud.githubusercontent.com/assets/4271415/3964233/53ecbb16-2786-11e4-94c1-1c9773ccefff.png)

![image](https://cloud.githubusercontent.com/assets/4271415/3964246/974bd694-2786-11e4-95d1-f2040e39151b.png)
目前看来是transform属性未成功写入新建节点元素。

**Comment by techird** [comment]
无法复现
