### ISSUE TITLE
节点拖拽

### ISSUE THREAD

**Issue by sprintsun** [fex-team/kityminder#118]
思维导图模式下，当我把一个位于主节点左边的节点拖拽到主节点右边去，然后在该节点上新增子节点，发现子节点还是会往左边扩散，建议能够增加对节点坐标的判断

**Comment by vidasilk** [comment]
只拖拽位置，也只是拖拽位置而已。左右是以默认顺序来进行分配的，所以要把需要换地方的节点拖拽到新位置后，注意，不要松开，靠近临近的兄弟节点，兄弟节点上方或者下方出现蓝色提示（不是直接移动成为子节点的蓝色边框，而是在节点的上方或者下方出现一个蓝色方块），松手，此节点的默认顺序就移动到你拖动的位置了。

**Comment by techird** [comment]
现在已经增加了布局的智能判断，谢谢！
