### ISSUE TITLE
建议增加 自由节点 和 联系 

### ISSUE THREAD

**Issue by foolhorse** [fex-team/kityminder#131]
导入.xmind 中如果有 自由节点和联系 都会转换父子节点，联系也会消失。
希望能添加自由节点 和 节点联系 的功能。

**Comment by techird** [comment]
好主意！

**Comment by lihshyang** [comment]
联系功能非常重要，强烈建议！

**Comment by zhangbobell** [comment]
您好，问题已经记录，我们将在后续版本中改进，问题转移到 [kityminder-editor #9](https://github.com/fex-team/kityminder-editor/issues/9)，欢迎关注！
