### ISSUE TITLE
文件保存失败，编辑内容丢失

### ISSUE THREAD

**Issue by feeloc** [fex-team/kityminder#14]
- 昨天画了一个小时的图，在公司最后一次保存的时候出错了，回家看应用数据里图没了，这让人很是气愤啊。
- 又重画了遍，生成PNG的时候又报错了。

``` js
This page contains the following errors:

error on line 1 at column 19582: Entity 'nbsp' not defined
Below is a rendering of the page up to the first error.
```

**Comment by techird** [comment]
真抱歉，使用 KityMinder 的时候给您带来了这么多的麻烦。根据您的描述，问题应该是在保存到云盘的时候发生的，我们会尽快去解决，尽量减小出错概率，并提高容错能力。

针对这个问题，我们会优先修复的，修复之后会第一时间回复您的。

针对现阶段的使用，有一个小技巧可以注意：

如果保存到网盘失败，或者希望有个稳妥的备份，可以把文件以 KityMinder（.km） 格式导出，导出的文件拖放到 KityMinder 的窗口内是可以导入的。

再次对给您带来的麻烦表示非常的抱歉！谢谢您的支持！

**Comment by campaign** [comment]
对于这次碰到的问题，我们给出如下改进方案
1.介于百度云盘接口的不稳定，我们会提供从本地倒入历史功能，会添加一个导入本地的按钮
2.由于浏览器的缓存机制，我们会在每次更新版本时，强制更新，保证您访问到最新的版本

我们会在今天及时更新 naotu.baidu.com。

谢谢

**Comment by techird** [comment]
草稿箱功能已上线。
