### ISSUE TITLE
导出svg，文字都错位

### ISSUE THREAD

**Issue by eexpress** [fex-team/kityminder#141]
看了下内容，居然没svg版本说明。还强制写上雅黑字体。

**Comment by techird** [comment]
Sorry，是我们的失误，确实写上 SVG 版本比较好。

Firefox 应该是支持 `dominant-baseline` 属性的，方便告诉我你的 Firefox 版本么？

另外，写上雅黑字体是为了让导出的样子和看到的样子保持一致，而且 SVG 修改字体也很方便的。

**Comment by eexpress** [comment]
刚才说错了。fx上是正常的。是eog/inkscape等软件显示的错位，但平时使用svg没碰到过错位的情况。

**Comment by techird** [comment]
可能是软件支持的不彻底，规范里有对[dominant-baseline](http://www.w3.org/TR/SVG11/text.html#DominantBaselineProperty)定义的。我们也没调研有哪些 SVG 软件，不过 Illustrator 是可以支持的。

**Comment by techird** [comment]
add version tag
