### ISSUE TITLE
编辑状态和选中状态视觉上区分不是很明显，在只用快捷键操作是很容易误操作

### ISSUE THREAD

**Issue by happlex** [fex-team/kityminder#156]
## 关于快捷键和UI

编辑状态和选中状态视觉上区分不是很明显，在只用快捷键操作是很容易误操作。  
比如，Enter键在编辑状态是结束编辑，在选中状态是插入兄弟结点... 造成经常错误地插入了兄弟结点。

**Comment by techird** [comment]
嗯嗯，谢谢反馈，我们会考虑优化方案！
