### ISSUE TITLE
Open MindManager 9 mmap file failed

### ISSUE THREAD

**Issue by vgamed** [fex-team/kityminder#166]
Error: Error while reading zip file.
    at <Anonymous> (ui/widget/notice.js:147:16)
    at descriptReason (ui/widget/notice.js:178:12)
    at error (ui/doc.js:83:19)
    at <async> Promise.callback
    at <async> Promise.invokeCallback
    at <async> Promise.publish
    at <async> Promise.callback

浏览器信息：Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/38.0.2125.111 Safari/537.36

**Comment by techird** [comment]
您好，方便把出错的文件发送到 kity@baidu.com 吗？
Thanks, would you mind sending this error file to kity@baidu.com?

**Comment by vgamed** [comment]
sorry. cannot expose the content of that file.
