### ISSUE TITLE
不能多行文本

### ISSUE THREAD

**Issue by iuphero** [fex-team/kityminder#168]
建议增加多行文本支持，例如在xmind中ctrl+center可以多行编辑

**Comment by techird** [comment]
您好，
脑图中用shift+enter可以换行。

谢谢您的反馈和支持！

在 2014年11月15日，18:53，Xfight <notifications@github.com<mailto:notifications@github.com>> 写道：

建议增加多行文本支持，例如在xmind中ctrl+center可以多行编辑
