### ISSUE TITLE
多个脑图文件同时编辑时，不能互相复制和粘贴。

### ISSUE THREAD

**Issue by miaogong** [fex-team/kityminder#173]
现在比较习惯用百度脑图做思路整理，同时打开几个窗口进行工作！

现在发现，不能在不同窗口的脑图文件之间进行分支的复制和粘贴工作。

希望官方团队考虑加上这个功能！谢谢！

**Comment by zhangbobell** [comment]
您好，问题已经记录，我们将在后续版本中改进，问题转移到 [kityminder-editor #26](https://github.com/fex-team/kityminder-editor/issues/26)，欢迎关注！
