### ISSUE TITLE
左边新增节点时布局没有做好调整

### ISSUE THREAD

**Issue by otw1248** [fex-team/kityminder#175]
![baidu naotu layout](https://cloud.githubusercontent.com/assets/9589597/5139217/ee9e2ac4-7195-11e4-88c8-ded003355422.jpg)

如图所示，Buffered Steam 是最后添加到节点，与之前的file Steam 已经有重叠了

**Comment by zhangbobell** [comment]
您好，问题已经记录，我们将在后续版本中改进，问题转移到 [kityminder-editor #24](https://github.com/fex-team/kityminder-editor/issues/24)，欢迎关注！
