### ISSUE TITLE
BUG：保存或导出成非.km后缀文件时，节点的链接丢失

### ISSUE THREAD

**Issue by joyexpr** [fex-team/kityminder#176]
发现把文件保存或导出成非.km格式时，脑图里节点的链接都丢失了

**Comment by zhangbobell** [comment]
您好，目前 Markdown 格式以及第三方格式都不能保存额外的数据（除了文本）。请先使用 km 格式保存，这个问题已经记录，我们将在后续版本中改进，问题转移到 [kityminder-editor #23](https://github.com/fex-team/kityminder-editor/issues/23)，欢迎关注！
