### ISSUE TITLE
文本被清空问题

### ISSUE THREAD

**Issue by w91** [fex-team/kityminder#178]
`Mac下chorme有此问题`
选中一个节点的情况下，使用option + command + 方向键切换tab，再切回来的时候选中节点的文本会被清空，很不方便。

**Comment by zhangbobell** [comment]
您好，问题已经记录，我们将在后续版本中改进，问题转移到 [kityminder-editor #22](https://github.com/fex-team/kityminder-editor/issues/22)，欢迎关注！
