### ISSUE TITLE
展开模式分两种

### ISSUE THREAD

**Issue by techird** [fex-team/kityminder#179]
单击保持默认行为展开下级节点；
双击展开整棵树。

收起的时候同理。

**Comment by zhangbobell** [comment]
您好，问题已经记录，我们将在后续版本中改进，问题转移到 [kityminder-editor #21](https://github.com/fex-team/kityminder-editor/issues/21)，欢迎关注！

**Comment by IndexXuan** [comment]
@zhangbobell @techird  请问这个 feature 怎么样了，很需要！
