### ISSUE TITLE
备注窗口太窄

### ISSUE THREAD

**Issue by techird** [fex-team/kityminder#180]

**Comment by gmouou** [comment]
备注窗口太窄  希望可以添加手动调节备注宽度功能

**Comment by techird** [comment]
Mark

**Comment by zhangbobell** [comment]
您好，问题已经记录，我们将在后续版本中改进，问题转移到 [kityminder-editor #20](https://github.com/fex-team/kityminder-editor/issues/20)，欢迎关注！
