### ISSUE TITLE
脑图没有存储到百度云/云盘中，当在其它浏览器打开时无法找到已经保存到云盘中的脑图

### ISSUE THREAD

**Issue by otw1248** [fex-team/kityminder#184]
![default](https://cloud.githubusercontent.com/assets/9589597/5195597/35ed3ed4-755a-11e4-8c59-43ed6438ee5c.jpg)

在chrome某帐号下使用脑图，可以打开、编辑，退出和再次登入此帐号能够正常工作。但是在其它帐号下的chrome或者firefox浏览器下 登录相同的帐号，里面没有任何已经保存过的脑图。

**Comment by zhangbobell** [comment]
您好，问题已经记录，我们将在后续版本中改进，问题转移到 [kityminder-editor #7](https://github.com/fex-team/kityminder-editor/issues/7)，欢迎关注！
