### ISSUE TITLE
脑图文件无法打开

### ISSUE THREAD

**Issue by otw1248** [fex-team/kityminder#185]
{
    "readyState": 4,
    "status": 404,
    "statusText": "Not Found",
    "headers": "x-pcs-request-id: MTAuMjE0LjcxLjYyOjgwODA6NDE2MTEyOTA2NjoyNy9Ob3YvMjAxNCAyMDozMjo1NSA=\r\nContent-Type: application/octet-stream\r\nContent-Length: 93\r\n",
    "responseText": "{\"error_code\":31066,\"error_msg\":\"file does not exist\",\"request_id\":4161129066}\n",
    "detail": {
        "error_code": 31066,
        "error_msg": "file does not exist",
        "request_id": 4161129066
    },
    "requestMethod": "read",
    "requestPath": "/apps/kityminder/java.mm",
    "requestUser": "otw1248",
    "requestParam": {
        "method": "download",
        "path": "/apps/kityminder/java.mm"
    },
    "requestDataType": "text",
    "description": "文件不存在"
}

浏览器信息：Mozilla/5.0 (X11; Linux i686) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/31.0.1650.63 Safari/537.36

**Comment by zhangbobell** [comment]
您好，问题已经记录，我们将在后续版本中改进，问题转移到 [kityminder-editor #7](https://github.com/fex-team/kityminder-editor/issues/7)，欢迎关注！
