### ISSUE TITLE
颜色和结构样式不能保存

### ISSUE THREAD

**Issue by jiazheng** [fex-team/kityminder#197]
选择颜色样式和格式后，再次打开又恢复默认了。

**Comment by techird** [comment]
您好，请使用 .km 格式。第三方格式目前不支持更多数据的保存。

在 2014年12月17日，下午12:14，jz <notifications@github.com<mailto:notifications@github.com>> 写道：

选择颜色样式和格式后，再次打开又恢复默认了。
