### ISSUE TITLE
用户反馈：包括简化打开文件的方式、修改标题建议等

### ISSUE THREAD

**Issue by zswang** [fex-team/kityminder#198]
## 用户反馈

> 来源：QQ群 王红亮
> 2014年12月25日
### 有一个体验很差

![image](https://cloud.githubusercontent.com/assets/536587/5554435/6e040652-8c90-11e4-81ff-f156a4f14df2.png)

就是，我制作了一些脑图后，想打开其中一个，在 云存储找到，然后 点击1下，打不开，双击还打不开。 
只有在 最近使用中，才可以 单击一次才能打开
为什么 云存储不可以呢？  因为给每个 作品后面，增加一个 打开的 按钮，点击一下就打开
我的电脑系统是  苹果系统，safi的浏览器 
### 第二个 体验痛点

无法修改标题名字。  点击进入修改状态，然后无法保持为修改后的名字； 太无节操了这个
### 第三个想法

能否在一个脑图，可以做无数个框架出来。   现在 智能新建一个，然后就一直下去了； 不能在同一页面，建立第二个；
### 第四个想法：

现在的脑图只能单向往下延展，不能形成闭环，不能相互连接。 也就是说只能延展的月来越大，不能最后 收一下

**Comment by techird** [comment]
@zswang 大叔辛苦！
