### ISSUE TITLE
请问如何导出为图片？

### ISSUE THREAD

**Issue by pengyuwei** [fex-team/kityminder#200]
我想导出导图为png或者jpg图片以便放在ppt里使用，但是导出都找不到导出的方法？莫非没有这种功能？（目前使用QQ截图，但是如果内容很多抓不全，不方便）

**Comment by techird** [comment]
您好，是可以导出成 PNG 图片的。目前不支持 IE 浏览器，请先通过 Chrome/Firefox/Safari 使用。
