### ISSUE TITLE
在ipad中用多个浏览器无法打开存储在百度云中的脑图

### ISSUE THREAD

**Issue by freechen** [fex-team/kityminder#202]
safari、qq浏览器、傲游都试过

**Comment by techird** [comment]
目前还不支持 Ipad、手机等移动设备

**Comment by jevanluo** [comment]
求支持ipad，感觉这个脑图的体检简直棒棒哒

**Comment by freechen** [comment]
希望能支持呢，有时候用iPad等平板需要演示，或与人沟通的时候，打不开。

**Comment by XC-Zhang** [comment]
在Android 5.0的Chrome上也不能打开，希望尽快支持～加油！

**Comment by lazyyz** [comment]
这个问题我昨天也遇到了，非常希望能够支持iPad

**Comment by zhangbobell** [comment]
您好，这个问题已经记录，我们将在后续版本中改进，问题转移到 [kityminder-editor #12](https://github.com/fex-team/kityminder-editor/issues/12)，欢迎关注！
