### ISSUE TITLE
链接丢失

### ISSUE THREAD

**Issue by upson** [fex-team/kityminder#203]
在脑图中添加链接，保存为MD格式，再次打开时链接没有了

**Comment by techird** [comment]
您好，目前 Markdown 格式以及第三方格式都不能保存额外的数据（除了文本）。请先使用 km 格式保存

**Comment by zhangbobell** [comment]
您好，问题已经记录，我们将在后续版本中改进，问题转移到 [kityminder-editor #23](https://github.com/fex-team/kityminder-editor/issues/23)，欢迎关注！
