### ISSUE TITLE
加入对数学公式的支持

### ISSUE THREAD

**Issue by elemount** [fex-team/kityminder#204]
节点的备注既然加入了对markdown的支持，是否可以考虑添加对MathJax的支持便捷输入数学公式，或者在选项中提供这一选项？

**Comment by zhangbobell** [comment]
您好，问题已经记录，我们将在后续版本中改进，问题转移到 [kityminder-editor #17](https://github.com/fex-team/kityminder-editor/issues/17)，欢迎关注！
