### ISSUE TITLE
无法保存

### ISSUE THREAD

**Issue by Lucces** [fex-team/kityminder#205]
{
    "readyState": 4,
    "status": 400,
    "statusText": "Bad Request",
    "headers": "ETag: 6032fa9f6bd137ed5e6ff69d7fd564b6\r\nx-pcs-request-id: MTAuMjE0LjcxLjQzOjgwODA6MjkzNzMxNDU4MDoxNC9KYW4vMjAxNSAxMDo1MToxOSA=\r\nContent-Type: text/html\r\nContent-Length: 71\r\nx-bs-request-id: MTAuMjE0LjcxLjQzOjgwODA6MjkzNzMxNDU4MDoxNC9KYW4vMjAxNSAxMDo1MToxOCA=\r\n",
    "responseText": "{\"error_code\":31112,\"error_msg\":\"exceed quota\",\"request_id\":2937314580}",
    "detail": {
        "error_code": 31112,
        "error_msg": "exceed quota",
        "request_id": 2937314580
    },
    "requestMethod": "write",
    "requestPath": "/apps/kityminder/test.km",
    "requestUser": "XXXX",
    "requestParam": {
        "method": "upload",
        "ondup": "overwrite",
        "path": "/apps/kityminder/test.km"
    },
    "requestDataType": "text",
    "description": "超出配额"
}

浏览器信息：Mozilla/5.0 (X11; Linux i686) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36

**Comment by zhangbobell** [comment]
您好，问题已经记录，我们将在后续版本中改进，问题转移到 [kityminder-editor #7](https://github.com/fex-team/kityminder-editor/issues/7)，欢迎关注！
