### ISSUE TITLE
【建议】希望可以加入多人协作功能

### ISSUE THREAD

**Issue by pcqpcq** [fex-team/kityminder#207]
参考https://www.processon.com
1. 在页面内可以直接聊天
2. 可以邀请别人加入协作编辑

非常感谢！

**Comment by zhangbobell** [comment]
您好，问题已经记录，我们将在后续版本中改进，问题转移到 [kityminder-editor #14](https://github.com/fex-team/kityminder-editor/issues/14)，欢迎关注！
