### ISSUE TITLE
无法保存到百度云网盘

### ISSUE THREAD

**Issue by yuanchenglu** [fex-team/kityminder#209]
{
    "readyState": 4,
    "status": 400,
    "statusText": "Bad Request",
    "headers": "ETag: f53cab99afb7540178c742175d1296c3\r\nx-pcs-request-id: MTAuMjE0LjI0My4xODo4MDgwOjEyNDI4MjIyOTQ6MjEvSmFuLzIwMTUgMTY6MjE6MDcg\r\nContent-Type: text/html\r\nContent-Length: 71\r\nx-bs-request-id: MTAuMjE0LjI0My4xODo4MDgwOjEyNDI4MjIyOTQ6MjEvSmFuLzIwMTUgMTY6MjE6MDcg\r\n",
    "responseText": "{\"error_code\":31112,\"error_msg\":\"exceed quota\",\"request_id\":1242822294}",
    "detail": {
        "error_code": 31112,
        "error_msg": "exceed quota",
        "request_id": 1242822294
    },
    "requestMethod": "write",
    "requestPath": "/apps/kityminder/思维导图/用户反馈系统--功能需求框图.km",
    "requestUser": "bluth111",
    "requestParam": {
        "method": "upload",
        "ondup": "overwrite",
        "path": "/apps/kityminder/思维导图/用户反馈系统--功能需求框图.km"
    },
    "requestDataType": "text",
    "description": "超出配额"
}

浏览器信息：Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.99 Safari/537.36

**Comment by zhangbobell** [comment]
您好，这是 PCS 储存的问题，我们将在后续版本中改进，问题转移到 [kityminder-editor #7](https://github.com/fex-team/kityminder-editor/issues/7)，欢迎关注！
