### ISSUE TITLE
可对脑图文件多人操作

### ISSUE THREAD

**Issue by blazecake** [fex-team/kityminder#213]
可以添加其他账号进来对指定的脑图文件操作，设置权限如查看、修改、删除等。多个人共同操作，类似git，svn多人协作管理。

**Comment by blazecake** [comment]
分享

**Comment by luobeng** [comment]
我也很希望有这个功能，强烈支持
有的时候，我们需要多人一起在多个地方协同进行脑图讨论和修改

**Comment by bigmidas** [comment]
对，最好能把每个修改人的信息体现在修改的地方，还有版本管理

**Comment by hsluoyz** [comment]
有道理

**Comment by zhangbobell** [comment]
您好，问题已经记录，我们将在后续版本中改进，问题转移到 [kityminder-editor #14](https://github.com/fex-team/kityminder-editor/issues/14)，欢迎关注！

**Comment by skyoflove111** [comment]
请问这个问题解决了吗？
