### ISSUE TITLE
ios和android为什么不能打开文件呢

### ISSUE THREAD

**Issue by cupjava** [fex-team/kityminder#218]
ios和android为什么不能打开文件呢

**Comment by brucefengnju** [comment]
之前用pad新建过脑图，也不能打开。可能是程序里面只监听了click事件，没有监听touch事件。

**Comment by zhangbobell** [comment]
您好，问题已经记录，我们将在后续版本中改进，问题转移到 [kityminder-editor #12](https://github.com/fex-team/kityminder-editor/issues/12)，欢迎关注！
