### ISSUE TITLE
节点关联

### ISSUE THREAD

**Issue by lovemyspring** [fex-team/kityminder#219]
xmind有个功能，能给在不同的节点之间进行关联设置，而在设计脑图时是不可避免的会出现不同节点关联的情况。后续咱们是否有支持的计划？

**Comment by zhangbobell** [comment]
您好，您提出的问题已经记录，我们将在后续版本中改进，问题转移到 [kityminder-editor #9](https://github.com/fex-team/kityminder-editor/issues/9)，欢迎关注！
