### ISSUE TITLE
手机访问乏力

### ISSUE THREAD

**Issue by clarkccc** [fex-team/kityminder#221]
手机没有app，用浏览器打开基本用不了，用的是iphone 上的chrome

**Comment by iamhankai** [comment]
Android用户同感，在手机上也想编辑。什么时候出个app或者手机适配版。

**Comment by zhangbobell** [comment]
您好，您提出的问题已经记录，我们将在后续版本中改进，问题转移到 [kityminder-editor #12](https://github.com/fex-team/kityminder-editor/issues/12)，欢迎关注！
