### ISSUE TITLE
文件名中包含 “/” 会默认识别为目录

### ISSUE THREAD

**Issue by yannisxu** [fex-team/kityminder#222]
例如:
我想新建一个文件名为 “产品/技术文档” 的脑图，实际情况下会创建一个产品的文件夹，然后再创建一个 “技术文档” 的脑图

**Comment by zhangbobell** [comment]
您好，您提出的问题已经记录，我们将在后续版本中改进，问题转移到 [kityminder-editor #11](https://github.com/fex-team/kityminder-editor/issues/11)，欢迎关注！
