### ISSUE TITLE
[建议]能否支持流程图？

### ISSUE THREAD

**Issue by xuhuan** [fex-team/kityminder#225]
如题，能否支持流程图。
支持可以自由连线？
支持可以拖放连线？
支持显示部分备注内容、链接、图片缩略图？
支持tudo list？
支持多个并列主题，适用于数据库设计、多个脑图在同一个页面内的情况、流程图等？
支持点击空白画布进行整屏拖动，现在只有点击到具体条目上才能进行拖动？

**Comment by zhangbobell** [comment]
您好，问题已经记录，我们将在后续版本中改进，您所说的最后一条现在是鼠标右键可以全屏拖动，其余问题转移到 [kityminder-editor #9](https://github.com/fex-team/kityminder-editor/issues/9) 和 [kityminder-editor #10](https://github.com/fex-team/kityminder-editor/issues/10)，欢迎关注！
