### ISSUE TITLE
无法插入关联关系

### ISSUE THREAD

**Issue by findeway** [fex-team/kityminder#228]
只有父子关系之间的联系，不够灵活。
1、在有时需要环形联系。
2、还有1到N再N到1的这种联系关系。
目前上面这两种都没法满足，建议以后能否改进，期待中！

**Comment by zhangbobell** [comment]
您好，问题已经记录，我们将在后续版本中改进，问题转移到 [kityminder-editor #9](https://github.com/fex-team/kityminder-editor/issues/9)，欢迎关注！
