### ISSUE TITLE
Tag 的管理

### ISSUE THREAD

**Issue by JerseyGood** [fex-team/kityminder#229]
1. 建议增加自定义Tag颜色
   定义了8个tag之后，新的tag只有灰色的了
2. 无法管理已经增加的Tag
   无法更改Tag的颜色，也无法删除曾经定义的Tag

Story：
一开始错误的使用了Tag功能，导致现在Tag功能失去了色彩

**Comment by zhangbobell** [comment]
问题已经记录，我们将在后续版本中增强 Tag 的功能，问题转移到 [kityminder-editor #8](https://github.com/fex-team/kityminder-editor/issues/8)，欢迎关注。

**Comment by fayeah** [comment]
请问怎么自定义tag颜色呢？
