### ISSUE TITLE
当删除整个文件夹时

### ISSUE THREAD

**Issue by chunhei2008** [fex-team/kityminder#232]
{
    "readyState": 4,
    "status": 404,
    "statusText": "Not Found",
    "headers": "x-pcs-request-id: MTAuMjE0LjQxLjI0OjgwODA6MTY0NDc3MzEyODozMS9NYXIvMjAxNSAxNzo0MDo0MCA=\r\nContent-Type: text/html\r\nContent-Length: 93\r\n",
    "responseText": "{\"error_code\":31066,\"error_msg\":\"file does not exist\",\"request_id\":1644773128}",
    "detail": {
        "error_code": 31066,
        "error_msg": "file does not exist",
        "request_id": 1644773128
    },
    "requestMethod": "list",
    "requestPath": "/apps/kityminder/1024mms",
    "requestUser": "chunhei2008",
    "requestParam": {
        "method": "list",
        "path": "/apps/kityminder/1024mms"
    },
    "requestDataType": "text",
    "description": "文件不存在"
}

浏览器信息：Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.115 Safari/537.36

**Comment by zhangbobell** [comment]
问题已经记录，是 PCS 储存的问题，我们将在后续版本中改进，问题转移到 [kityminder-editor #7](https://github.com/fex-team/kityminder-editor/issues/7)，欢迎关注。
