### ISSUE TITLE
强烈要求脑图优先完成导出png图片的功能，这是迈向实用最重要的一个功能

### ISSUE THREAD

**Issue by pengyuwei** [fex-team/kityminder#234]
脑图画出来干什么用？就是要展示给大家看！

强烈要求脑图优先完成导出png图片的功能，这是迈向实用最重要的一个功能，望采纳！

**Comment by zhangbobell** [comment]
您好，现在的脑图已经具有到处成 png 和 svg 的功能，“保存”->“导出到本地”即可。
