### ISSUE TITLE
输入编辑节点 快捷键相关的问题

### ISSUE THREAD

**Issue by maolion** [fex-team/kityminder#236]
在节点上输入信息时，可能我想按 Esc 来取消一次修改。但按Esc 直接刷到主菜单的面板上。。。。。。

**Comment by techird** [comment]
@maolion 收到！

**Comment by zhangbobell** [comment]
问题已经记录，我们将在后续版本中改进，问题转移到 [kityminder-editor #5](https://github.com/fex-team/kityminder-editor/issues/5)，欢迎关注。
