### ISSUE TITLE
bug:节点和隐藏子节点图标重合

### ISSUE THREAD

**Issue by IrisZhang** [fex-team/kityminder#237]
![qq 20150408091247](https://cloud.githubusercontent.com/assets/9741458/7037092/98f99f08-ddcf-11e4-98af-18ab0d74fb07.png)

**Comment by zhangbobell** [comment]
您好，问题已经记录，我们将在后续版本中改进，问题转移到 [kityminder-editor #4](https://github.com/fex-team/kityminder-editor/issues/4)
