### ISSUE TITLE
希望增加一个浮动的显示的备注

### ISSUE THREAD

**Issue by William17** [fex-team/kityminder#286]
现在的备注需要点击才看到. 导出为图片的时候根本看不到
希望能添加浮动的,不需要点击的,直接显示在图上的.

**Comment by zhangbobell** [comment]
导出的时候备注的显示已经有一些用户反馈过了，这功能已经列入到了开发计划中，另外，这个库已经不更新了，以后建议提 issue 前往 [kityminder-editor](https://github.com/fex-team/kityminder-editor)，以便得到更及时的回复。
