### ISSUE TITLE
脑图保存失败！！！！

### ISSUE THREAD

**Issue by ghost** [fex-team/kityminder#289]
TypeError: Illegal constructor
    at <Anonymous> (lib/fio/provider/netdisk/netdisk.js:135:40)
    at handle (lib/fio/src/fio.js:577:40)
    at <async> Promise.callback
    at <async> Promise.invokeCallback
    at <async> Promise.publish
    at <async> Promise.callback

浏览器信息：Mozilla/5.0 (X11; Linux i686) AppleWebKit/535.19 (KHTML, like Gecko) Ubuntu/11.04 Chromium/18.0.1025.168 Chrome/18.0.1025.168 Safari/535.19

**Comment by zhangbobell** [comment]
这个库不再更新了，二次开发建议前往 [kityminder-editor](https://github.com/fex-team/kityminder-editor)。
