### ISSUE TITLE
删除中心节点导致页面卡住

### ISSUE THREAD

**Issue by yb7** [fex-team/kityminder#29]
影响版本      1.1.1
测试浏览器  Chrome
Step 1.  绘制任意的脑图
Step 2.  选中中心节点，点击DELETE按键（非mac键盘）
Step 3.  发现卡死，无法点击任何其他的node

![image](https://cloud.githubusercontent.com/assets/678122/2576151/16243c82-b968-11e3-835b-044482036448.png)

**Comment by campaign** [comment]
1.1.2修复了这个问题
