### ISSUE TITLE
添加箭头功能

### ISSUE THREAD

**Issue by yreme** [fex-team/kityminder#290]
目前百度脑图只能做`树状结构树`，但很多情况下需要各个元素都有相互作用，能否添加`箭头`的功能

**Comment by jianzi0307** [comment]
支持，需要 “联系” 功能，类似xmind

**Comment by jianzi0307** [comment]
还没有类似的功能哦，没有计划吗

**Comment by zhangbobell** [comment]
你所提到的自由连线功能已经列入了开发计划，另外，这个库已经不更新了，以后建议提 issue 前往 [kityminder-editor](https://github.com/fex-team/kityminder-editor)，以便得到更及时的回复。
