### ISSUE TITLE
备注内容不支持复制粘贴

### ISSUE THREAD

**Issue by wuhx** [fex-team/kityminder#291]
环境：Mac + Chrome 45

脑图的结构可视化非常好用，强化一下备注功能，可以替代笔记软件：）

**Comment by zhangbobell** [comment]
很抱歉现在才看到，问题已经于去年修复了，另外，这个库已经不更新了，以后建议提 issue 前往 [kityminder-editor](https://github.com/fex-team/kityminder-editor)，以便得到更及时的回复。
