### ISSUE TITLE
从xmind导入的格式与结构不是很理想

### ISSUE THREAD

**Issue by ccjoe** [fex-team/kityminder#293]
从xmind导入的格式与结构不是很理想

**Comment by ccjoe** [comment]
而且仅能处理树形结构，子节点之间的联系还不能处理。
目前使用起来与桌面版类似软件差距还是很大。

**Comment by zhangbobell** [comment]
目前导入的第三方格式不支持备注、自由连线等信息，我们会在未来逐步完善。另外，这个库已经不更新了，以后建议提 issue 前往 [kityminder-editor](https://github.com/fex-team/kityminder-editor)，以便得到更及时的回复。
