### ISSUE TITLE
这里导出的kityminder 在Edge浏览器报错，但百度脑图官网却没有这个问题

### ISSUE THREAD

**Issue by weidays** [fex-team/kityminder#294]

**Comment by weidays** [comment]
![image](https://cloud.githubusercontent.com/assets/3984392/12572060/3ef8af78-c422-11e5-9363-f10510ca3524.png)
![image](https://cloud.githubusercontent.com/assets/3984392/12572052/3794d8e2-c422-11e5-85f8-a53829e6a8e6.png)

**Comment by zhangbobell** [comment]
这个库不再更新了，二次开发建议前往 [kityminder-editor](https://github.com/fex-team/kityminder-editor)。
