### ISSUE TITLE
需求:能否支持为节点增加超链接？

### ISSUE THREAD

**Issue by xuejiancheng** [fex-team/kityminder#295]
希望可以给节点增加超链接，点击这个节点的超链接就可以直接跳转到对应的URL。 @BaiduFE

**Comment by zhangbobell** [comment]
目前 kityminder-editor 已经具备添加超链接的功能，另外，这个库不再更新了，二次开发建议前往 [kityminder-editor](https://github.com/fex-team/kityminder-editor)。
