### ISSUE TITLE
需求:希望可以从一个脑图的节点直接跳转到另外一个脑图

### ISSUE THREAD

**Issue by xuejiancheng** [fex-team/kityminder#296]
应用场景：当一个脑图过大时，可以再分解成多个子脑图来呈现。这些子脑图也存在上下级或同级的逻辑关系。如果支持脑图间的跳转，那在看的时候可以保持思维的连贯性。

**Comment by zhangbobell** [comment]
脑图之间的链接跳转已经加入了开发计划，另外，这个库已经不更新了，以后建议提 issue 前往 [kityminder-editor](https://github.com/fex-team/kityminder-editor)，以便得到更及时的回复。
