### ISSUE TITLE
执行grunt 报如下错误

### ISSUE THREAD

**Issue by xuzhitong89** [fex-team/kityminder#297]
Running "less:compile" (less) task

> > FileError: '../../../../lib/fui/theme/default/fui.all.css' wasn't found in ui/theme/default/css/import.less on line 1, column 1:
> > 1 @import (less) "../../../../lib/fui/theme/default/fui.all.css";
> > 2 @import (less) "../../../../lib/bower/codemirror/lib/codemirror.css";
> > Warning: Error compiling ui/theme/default/css/import.less Use --force to continue.

**Comment by bulldog478** [comment]
同样的问题

**Comment by zhangbobell** [comment]
可能需要更新子模块吧，详见readme 的[安装部分](https://github.com/fex-team/kityminder#安装)。另外，二次开发不建议基于 kityminder，建议前往 [kityminder-editor](https://github.com/fex-team/kityminder-editor)。

**Comment by zhiyue** [comment]
@xuzhitong89 @bulldog478 尝试使用:

```
bower install
```
