### ISSUE TITLE
4月11日2：17左右，我打算将脑图生成分享链接，结果报错，然后服务器挂了。。。

### ISSUE THREAD

**Issue by yalishizhude** [fex-team/kityminder#298]
这是正常的升级维护么？
如果是建议挂个维护页面告知用户升级完成时间~
如果不是还请修复bug~

**Comment by zhangbobell** [comment]
抱歉刚看到，4 月 11 日 2:17 左右我们没有进行升级维护，你这个问题还存在么？

**Comment by zhangbobell** [comment]
这个库已经不更新了，以后建议提 issue 前往 [kityminder-editor](https://github.com/fex-team/kityminder-editor)，以便得到更及时的回复。
