### ISSUE TITLE
节点文字中含有&nbsp;的时候，导出png和svg会有问题

### ISSUE THREAD

**Issue by Akikonata** [fex-team/kityminder#30]
无法导出png，导出的svg文件在浏览器里打开的时候会显示&nbsp;无法解析。

**Comment by ronnyKJ** [comment]
http://stackoverflow.com/questions/8257711/how-to-transform-nbsp-in-xslt
这种方式可以解决svg导出，png依然不行，用了折中方式，后续改进。

**Comment by techird** [comment]
PNG导出OK（commit 3cd04eb）
