### ISSUE TITLE
在线导入本地km文档时，出现多个km后缀

### ISSUE THREAD

**Issue by VeniZhang** [fex-team/kityminder#300]
![qq 20160430204241](https://cloud.githubusercontent.com/assets/16594245/14935888/23ae8cd2-0f14-11e6-98b8-259da21d47f8.jpg)

如上图所示，需要自己重命名，将km去掉。

**Comment by zhangbobell** [comment]
收到问题，我们会在下个更新修复，另外，这个库已经不更新了，以后建议提 issue 前往 [kityminder-editor](https://github.com/fex-team/kityminder-editor)，以便得到更及时的回复。
