### ISSUE TITLE
如何进入编辑页面

### ISSUE THREAD

**Issue by bu2zhouzhu** [fex-team/kityminder#310]
## 问题描述

dev分支.  按照 [README.md](https://github.com/fex-team/kityminder/blob/dev/README.md) 描述的命令安装完成后，打开`dist/index.html`，显示的是 “马上开启，使用百度帐号登陆”界面.
![](http://i.imgur.com/bnh7Rbq.png)。

点击“马上开启”按钮跳转到 https://openapi.baidu.com/oauth/2.0/authorize 开头的一个网站，页面显示“您遇到了错误！错误代码：redirect_uri_mismatch 错误信息：Invalid redirect uri”.
![](http://i.imgur.com/lscZr6p.png)

## 问题: 
1. 能否不使用百度帐号进入脑图编辑页。本地安装的意义就是不使用百度帐号。
2. 如何进入编辑页面。

---

其它信息:
打开`dist/edit.html的`界面如图所示。顶部工具栏消失，完全无法使用
![](http://i.imgur.com/X9AAk9p.png)

**Comment by zhangbobell** [comment]
二次开发请基于 [kityminder-editor](https://github.com/fex-team/kityminder-editor)，本项目各模块（用户认证、文件储存）耦合过多，有些服务也已经下架，所以本地不能跑起来。

**Comment by zli2014** [comment]
谢谢，让我知道二次开发去找哪个项目了
