### ISSUE TITLE
原来的数据没了。。。

### ISSUE THREAD

**Issue by cgcgbcbc** [fex-team/kityminder#49]
之前做了个比较重要的文件后来演讲完了就没用了，刚发现原来的应用数据都没了。。

**Comment by campaign** [comment]
你的数据是不会丢失的，你可以去pan.baidu.com,在“我的应用数据“－》"kityminder“下边，看你的数据是否存在。
出现这种情况，一般是云盘认为你的登录过期了，但他们提供的接口暂时不能让km在你的本地发现这个问题，所以数据不能再次打开，你可以选注销，重新登录，或者清除cookie，重新登录，都可以重新打开旧的数据。
这个问题我们会即使给出解决方案。
谢谢

**Comment by cgcgbcbc** [comment]
@campaign 是在pan.baidu.com我的应用数据->kityminder下边消失掉了...
今天打开的时候因为隔了很久或者是因为域名换了的缘故没有cookie，然后就不在登录状态，然后我点了下登录，然后没有出现之前的图，下拉菜单里只有到网盘管理文件，然后进去发现我的应用数据kityminder里面没有数据...

**Comment by cgcgbcbc** [comment]
@campaign 另外我最后一次使用是在3月12日从已经失效的http://fex-team.baidu.com/kityminder/dist地址登入使用的...不知道在chrome里有没有办法看到已经无法打开的地址所使用的local storage之类的..
