### ISSUE TITLE
support txt2map

### ISSUE THREAD

**Issue by nutsh** [fex-team/kityminder#5]
Hi there,

Is it possible to support txt2map?

for example

```
Main Topic
  subTopic1
  subTopic2
    third-subTopic1
    third-subTopic1
  subTopic3
```

and call some web api {url}/map/txt2map

and it will return an generated png file for the web?

It's nice for sharing...

Thanks & Best Regards,
Ajax

**Comment by techird** [comment]
Hi, Ajax:

Thanks for your suggestion.

Currently we use front-end code to export the minder map into png format. In this case, we can easily generate a hyper link to the png image, but with difficulties give a binary png image response.

We will take your suggestion into consideration, use the back-end code to support export of more file formats (such as .xmind, .freemind, .mmap and so on) in the future.

Thanks,
Techird@f-cube, FEX

**Comment by techird** [comment]
短期不会支持
