### ISSUE TITLE
建议加入 F2 编辑的快捷键

### ISSUE THREAD

**Issue by zswang** [fex-team/kityminder#56]
如果不用鼠标怎么进入编辑文字的状态，貌似现在没有，按 Windows 的习惯是 F2

**Comment by hefangshi** [comment]
#28 提过啦；)

**Comment by techird** [comment]
和 #28 重复，关闭。另外，集鹄耐不住，已经自己改了代码加了 F2 编辑这个功能。已 merge（#60），下版本会上线。
