### ISSUE TITLE
导出SVG图片显示不正常

### ISSUE THREAD

**Issue by WhiteWorld** [fex-team/kityminder#57]
导出后，用浏览器打开只杂乱显示部分节点

**Comment by Akikonata** [comment]
这个是因为线条和文字都是白色的，浏览器背景也是白色的，所以就看不出来了。

**Comment by WhiteWorld** [comment]
除此之外，显示还是有问题，我在浏览器里打开导出的svg图片，发现图片只显示导出时的那个窗口里包含的部分，缩小才能看到其他的，但是格式已经有问题了。
（问题不好叙述，可以导出一下我的脑图：http://naotu.baidu.com/?shareId=3trquop8f2i）

**Comment by Akikonata** [comment]
请问你用的是什么浏览器？目前导出功能在chrome下支持会比较好。

**Comment by WhiteWorld** [comment]
Win7  
Chrome 最新版本 34.0.1847.131 m

**Comment by Akikonata** [comment]
感谢反馈，你发的那个思维导图我用mac上的chrome导出了，暂时没有发现问题，win7上我们会尽快重现修复。
