### ISSUE TITLE
导出功能bug

### ISSUE THREAD

**Issue by kyozhou** [fex-team/kityminder#6]
macbook pro retina 13 导出的截图不对
![kityminder_1393928912685](https://f.cloud.github.com/assets/1305884/2320021/f75d8ba0-a387-11e3-8184-ddbd417b6466.png)

**Comment by angrilove** [comment]
window8,chrome 33.0.1750.146 m,导出有问题，过多的节点，下方的图不显示，如原图是，
![image](https://f.cloud.github.com/assets/5861092/2354877/956743a8-a5cd-11e3-99f5-cd53f9552719.png)
导出后则为
![12](https://f.cloud.github.com/assets/5861092/2354886/ca037c44-a5cd-11e3-852d-de48a73fb30a.png)

**Comment by techird** [comment]
谢谢反馈！这个问题正在修复，和 #2 是同一个 issue。

**Comment by techird** [comment]
已经修复
