### ISSUE TITLE
关于是否可以添加一些新的功能的若干建议？

### ISSUE THREAD

**Issue by sumilao** [fex-team/kityminder#65]
1.用脑图做课程整理的时候像有些公式的格式没有办法打出来，所以可否插入图片（这样可能会显得结构很乱，图片大小也不好控制，但是也许会有一定的用处）或者像word对象里面一样可以输入公式。（图中是用word打出的数学公式）
![qq20140506132507](https://cloud.githubusercontent.com/assets/7496407/2886180/dc6bd3c8-d4de-11e3-9d85-980fd4f2af13.png)

2.（1）脑图的功能一般都是由树状结构向外拓展的，可是就像家族谱系一样，如果你的亲戚和外来者结婚，那么必然会有一个和所有之前的节点都无关的节点和树中的某一节点建立联系，其它脑图绘制之中应该也有引入外来信息之类的东西符合这个例子。
（2）如果假设他们又生了一个孩子，那么会有两个节点合并成一个子节点才能更好的表示之间的关系，像其它脑图之中应该也有由已知推出结论可以用到这种结构，所以能否进行以下脑图结构的扩充？

3.最后感觉脑图的设计还可以改成计划完成路线图，设置几个节点和最终目标，然后添加一些其它东西（时间，完成情况，预计完成时间，需要东西之类的）。
![qq20140506131634](https://cloud.githubusercontent.com/assets/7496407/2886181/dedbbd4e-d4de-11e3-8521-0c55e2369a43.png)

ps：第一次用脑图的软件，之前也没有接触过，所以问题提的可能肤浅，希望能多多包涵，另外感觉kityminder做的很好，口头支持一下。

**Comment by Akikonata** [comment]
感谢对我们的支持^_^您的建议我们会参考并进一步整理成具体的需求～
关于公式的支持方面，由于存在技术上的难点，所以近期可能暂时还支持不了，欢迎同时关注我们的公式编辑器项目 https://github.com/fex-team/kityformula

**Comment by techird** [comment]
插入图片的功能下个版本发布，truck上的版本已有。
