### ISSUE TITLE
节点注释/备注功能

### ISSUE THREAD

**Issue by techird** [fex-team/kityminder#68]
支持给某一个节点添加一个长文本的备注，这样[导出成 Markdown 的时候](https://github.com/fex-team/kityminder/issues/58)主题下的正文就可以有内容了。

**Comment by marklma** [comment]
建议同时也考虑freemind格式的备注啊、注释导入的兼容性

**Comment by techird** [comment]
嗯嗯，谢谢您的建议

**Comment by techird** [comment]
done by 6916bcc42abe24d2dcecbe64b2b531eac993317a
