### ISSUE TITLE
百度脑图只出现根节点，树叶不出现了。访问也变慢了

### ISSUE THREAD

**Issue by wushanchao** [fex-team/kityminder#73]

**Comment by Akikonata** [comment]
具体能否截图看一下？因为目前暂时关闭了向下的布局模式，可能之前用了向下布局的显示会有问题……这个问题周一会修复。

**Comment by campaign** [comment]
已经修复并更新了线上。我们暂时去掉了向下的主题，是因为主题这块，我们没有想清楚，现在的主题太过简单了，后续我们会重新上线主题这块。
感谢支持kityminder.
有问题，可随时告知我们。
