### ISSUE TITLE
当节点折叠时，连续按右键会出现不能选择节点的问题

### ISSUE THREAD

**Issue by zswang** [fex-team/kityminder#74]
### 问题

不能选中节点
### 重现步骤
1. 新建一个脑图
2. 添加两级子节点
   节点1
   　┗节点2
   　　┗节点3
3. 折叠中间级的节点
   节点1
   　+节点2
4. 刷新页面
5. 按键盘右键两次
   出现异常：`Uncaught TypeError: Cannot read property 'getContent' of undefined`
6. 鼠标点击任意位置
   出现异常：`Uncaught TypeError: Cannot read property 'setOpacity' of undefined`

**Comment by techird** [comment]
现在还不能复现，明天找你~

**Comment by campaign** [comment]
已经修复上线
