### ISSUE TITLE
请添加取消分享功能

### ISSUE THREAD

**Issue by yf-hk** [fex-team/kityminder#76]
分享过后的脑图貌似没有办法取消分享？另外未分享的脑图，是否可以保证其他用户没有任何办法访问到？

**Comment by techird** [comment]
您好，分享的脑图没有取消的功能，如果确实要取消，请把分享的连接发到 kity@baidu.com。

未分享的脑图其他用户访问不到，请放心。

**Comment by yf-hk** [comment]
是否以后可以添加取消分享功能？感觉不太合理。另外从网盘删除文件后，再进去脑图好像还是可以访问，不知是否可以彻底删除？

**Comment by techird** [comment]
分享的时候创建的是副本，这块后续会优化的。
