### ISSUE TITLE
脑图 1.3.0 功能列表及 UI 升级后的交互描述

### ISSUE THREAD

**Issue by techird** [fex-team/kityminder#78]
整理一下 1.3.0 应有的功能，以及其交互的详细描述。
## 文件名区
- [ ] 显示文件名
- [ ] 点击修改文件名
## 常用功能区
- 左侧
  - [ ] `打开`：菜单
    - [ ] `网盘文件...` -> 网盘文件浮层
    - [ ] `本地文件...` -> 文件选择对话框
    - [ ] `草稿箱...` -> 草稿箱对话框
    - [ ] _分割线_
    - [ ] _最近打开的文件（5个）_
  - [ ] `保存`：按钮带下拉菜单
    - [ ] `到网盘...` -> 网盘
    - [ ] `纯文本（.txt）到本地` -> 下载文件
    - [ ] `KityMinder 格式（.km）到本地` -> 下载文件
    - [ ] `SVG 文件（.svg）到本地` -> 下载文件
    - [ ] `PNG 文件（.png）到本地` -> 下载文件
  - [ ] `撤销`：按钮（图标 + 文本）-> 直接执行
  - [ ] `重做`：按钮（图标 + 文本）-> 直接执行
  - [ ] `帮助`：按钮（图标 + 文本）-> 出对话框
- 右侧
  - [ ] 登录（图标 + 文本）-> 直接跳转
  - [ ] 分享（图标 + 文本）-> 出分享对话框
  - [ ] 搜索（搜索框）-> 定位到包含关键字的节点
## 功能区

功能区模仿 Ribbon 界面，按功能分类列出 3 个选项卡依次为：外观、节点、视图

选项卡点击后展开相应的功能区域，再次点击能收起。
- [ ] 外观

![image](https://cloud.githubusercontent.com/assets/1901286/3409093/790fb74e-fdd4-11e3-986a-153da0d4a9ba.png)
- [ ] 节点

![image](https://cloud.githubusercontent.com/assets/1901286/3409098/9408e214-fdd4-11e3-988e-164e7e033777.png)
- [ ] 视图

![image](https://cloud.githubusercontent.com/assets/1901286/3409100/9afcb212-fdd4-11e3-8c7e-106ace7f0e39.png)

**Comment by Alsiso** [comment]
请问1.3.0版本预计发布的时间是？ 现在使用中由于文件列表过长，已经超出窗口显示范围，部分文件名称被隐藏，导致不能再次激活；追问：1.3.0版本否能保存MD文件？

**Comment by techird** [comment]
因为功能点较多，需要到八月底。MD格式看时间是否充裕再决定支持否。
