### ISSUE TITLE
firefox下报错

### ISSUE THREAD

**Issue by asoqa** [fex-team/kityminder#81]
KityMinder v1.1.3.1版本， firefox报错信息如下（chrome下显示正常）：

TypeError: a.Utils is undefined

... mouseup mousemove mousewheel DOMMouseScroll touchstart touchmove touchend",this...

kitymin...6332199 (第 10 行)
TypeError: KM.getKityMinder is not a function

window.km = KM.getKityMinder('kityminder');

index.html (第 65 行)
TypeError: $.kmuidropmenu is not a function

divider: true

social....6332199 (第 127

**Comment by techird** [comment]
应该是文件引用错误，请仔细检查。
