### ISSUE TITLE
ZeroClipboard.min.js路径写死了

### ISSUE THREAD

**Issue by asoqa** [fex-team/kityminder#82]
ZeroClipboard.min.js脚本中
var s={moviePath:ZeroClipboard.swf"...
这个路径写死了，当外部路径变化时，浏览器会报错，建议优化一下

**Comment by techird** [comment]
[ZeroClipboard](https://github.com/zeroclipboard/zeroclipboard) 是引用的一个第三方库，用来操作剪贴板。官方 API 有说明如何更改 swf 文件的路径：

``` js
ZeroClipboard.config({
    swfPath: 'ZeroClipboard.swf'
});
```
