### ISSUE TITLE
能否触发后才渲染

### ISSUE THREAD

**Issue by asoqa** [fex-team/kityminder#83]
现在默认是吧所有js文件加载下来，然后直接渲染出来。
   能否提供api，使得默认是不显示的，只有当触发某个事件后，调用此api渲染kityminder。
   我现在用bootstrap tab试验的情况，貌似是不支持的，代码里有些地方时写死的。

**Comment by techird** [comment]
现在还没有类似的API，不过你可以在切换到脑图的 tab 的时候再创建脑图。如果要渲染的数据发生改变，调用实例上的 importData() 来更新

**Comment by asoqa** [comment]
这个成本有点高啊，我需要在切换到对应的tab后，动态加载所有的js然后再初始化

**Comment by techird** [comment]
那你也可以这样，先创建一个空的脑图实例，需要渲染的时候再调用 importData()
